# 启用开发配置
spring:
  profiles:
    active: dev
    


# 自定义属性
com:
  didispace:
    blog:
      name: 程序猿DD
      title: Spring Boot教程
      desc: ${com.didispace.blog.name}正在努力写《${com.didispace.blog.title}》
      # 随机字符串
      value: ${random.value}
      # 随机int
      number: ${random.int}
      # 随机long
      bignumber: ${random.long}
      # 10以内的随机数
      test1: ${random.int(10)}
      # 10-20的随机数
      test2: ${random.int[10,20]}


